swipes:
  - name: "Next Desktop"
    detection: "e+r+t"
    command: "control(alt(right))"
  - name: "Previous Desktop"
    detection: "o+i+u"
    command: "control(alt(left))"
  - name: "Next Window"
    detection: "s+d+f"
    command: "alt(tab)"
  - name: "Max Screen"
    detection: "v+f"
    command: "super(up)"
hands:
  - name: "Point"
    position:
      mirror: "CUCCC"
    action: "MoveCursorByIndex"
  - name: "Point"
    position:
      mirror: "CRCCC"
    action: "MoveCursorByIndex"
  - name: "Peace"
    position:
      mirror: "XRRUC"
    action: "MoveCursorByIndexTwo"
  - name: "Peace"
    position:
      mirror: "XRRCC"
    action: "MoveCursorByIndexTwo"
  - name: "Rock Star"
    position:
      mirror: "XURRU"
    action: "NotImplemented"
  - name: "Flat Rock Star"
    position:
      mirror: "XRCCR"
    action: "TabOnThumb"
  - name: "Left Thumb Out"
    position:
      left:  "UCCCC"
      right: "CCCCC"
    action: "MoveRight"
  - name: "Right Thumb Out"
    position:
      left:  "CCCCC"
      right: "UCCCC"
    action: "MoveLeft"
  - name: "Lefthanded L"
    position:
      left: "UCCCR"
      right: "CCCCC"
    action: "SelectRight"
  - name: "Righthanded L"
    position:
      left: "XXXXX"
      right: "UCCCR"
    action: "SelectLeft"
  - name: "Double L"
    position:
      left: "URCCC"
      right: "URCCC"
    action: "SelectAll"
  - name: "Thumbless pointing"
    position:
      left: "URCCC"
      right: "XXXXX"
    action: "JumpUp"
  - name: "Pinky"
    position:
      mirror: "RRRRU"
    action: "NotImplemented"