global:
  arrow_sensitivity: 1
  web_cam_number: 1
  flipped_camera: true
swipes:
  - name: "Next Desktop"
    detection: "e+r+t"
    command: "control(left)"
  - name: "Previous Desktop"
    detection: "o+i+u"
    command: "control(right)"
  - name: "Next Window"
    detection: "s+d+f"
    command: "alt(tab)"
  - name: "Max Screen"
    detection: "v+f"
    command: "super(up)"
hands:
  - name: ">.<"
    tap:
      left: "XOXXX"
      right: "XOXXX"
      threshold: .2
    action: "FindAndReplace"
  - name: "Point"
    position:
      mirror: "CUCCC"
    action: "MoveCursorByIndex"
  - name: "Point"
    position:
      mirror: "CRCCC"
    action: "MoveCursorByIndex"
  - name: "Peace"
    position:
      mirror: "XRRUC"
    action: "MoveCursorByIndexTwo"
  - name: "Peace"
    position:
      mirror: "XRRCC"
    action: "MoveCursorByIndexTwo"
  - name: "Rock Star"
    position:
      mirror: "XURRU"
    action: "NotImplemented"
  - name: "Flat Rock Star"
    position:
      mirror: "XRCCR"
    action: "ChangeWindow"
  - name: "Left Thumb Out"
    position:
      left:  "UCCCC"
      right: "CCCCC"
    action: "MoveRight"
  - name: "Right Thumb Out"
    position:
      left:  "CCCCC"
      right: "UCCCC"
    action: "MoveLeft"
  - name: "Lefthanded L"
    position:
      left: "UCCCR"
      right: "CCCCC"
    action: "SelectRight"
  - name: "Righthanded L"
    position:
      left: "XXXXX"
      right: "UCCCR"
    action: "SelectLeft"
  - name: "Double L"
    position:
      left: "URCCC"
      right: "URCCC"
    action: "SelectAll"
  - name: "Three up"
    position:
      left: "CRRRU"
      right: "XXXXX"
    action: "JumpUp"
  - name: "New+Index"
    position:
      left: "CRRRR"
      right: "CXXXX"
    action: "NewWindow"
  - name: "New+Middle"
    position:
      left: "CRRRR"
      right: "CXXXX"
    action: "CloseWindow"